version: '3'
services: 
  backend:
    build: 
      context: ./application
    ports: 
      - '80:5000'
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0mp4ny
      MYSQL_DATABASE: weather_station
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
