// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Station.Persistence;

#nullable disable

namespace Weather.Station.Migrations
{
    [DbContext(typeof(DaoContext))]
    [Migration("20220602132105_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Weather.Station.Model.WeatherStationValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Anemometer")
                        .HasColumnType("double");

                    b.Property<double>("Humidity")
                        .HasColumnType("double");

                    b.Property<DateTime>("Instant")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Pressure")
                        .HasColumnType("double");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<double>("UV")
                        .HasColumnType("double");

                    b.Property<double>("WaterSensor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("WeatherStation");
                });
#pragma warning restore 612, 618
        }
    }
}
